FROM python:3.10-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libmagic1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install lingua-language-detector~=1.3.2

COPY . .

EXPOSE 5000

CMD [ "python", "run_server.py" ]